### PR TITLE
Default ClientOptions.timeoutOptions to TimeoutOptions.enabled()

### PR DESCRIPTION
**Pull request by thachlp**
Issue #2518 
Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/main/.github/CONTRIBUTING.md).
- [ ] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request.
- [x] You applied code formatting rules using the `mvn formatter:format` target. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.

### CODE REVIEW

**Comment by tishun** [comment]
Hey @thachlp , there is a number of tests that fail after this change, most likely because they do not expect these timeout options to be set by default. Could you address this?

**Comment by tishun** [comment]
> Hey @thachlp , there is a number of tests that fail after this change, most likely because they do not expect these timeout options to be set by default. Could you address this?

Also make sure you merge the fix from #2948

**Comment by thachlp** [comment]
> Hey @thachlp , there is a number of tests that fail after this change, most likely because they do not expect these timeout options to be set by default. Could you address this?

Let me check

**Review by tishun — APPROVED** [review]
Looks good to me

Right now this fix is targeted for 7.x, I'll discuss this in the team and see if we should merge it to a 7.x branch or change the target version. I am personally leaning for changing the target branch.

**Comment by thachlp** [comment]
> Looks good to me
> 
> Right now this fix is targeted for 7.x, I'll discuss this in the team and see if we should merge it to a 7.x branch or change the target version. I am personally leaning for changing the target branch.

Thanks @tishun

**Pull request merged**
