### PR TITLE
Support HSCAN with NOVALUES argument

### PR DESCRIPTION
**Pull request by gerzse**
Issue #2763

HSCAN has a new argument called NOVALUES. The effect is that only the keys in the hash are returned, without associated values.

Make sure that:

- [ ] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/main/.github/CONTRIBUTING.md).
- [ ] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request.
- [ ] You use the code formatters provided [here](https://github.com/lettuce-io/lettuce-core/blob/main/formatting.xml) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.

### CODE REVIEW

**Review by mp911de — CHANGES_REQUESTED** [review]
Generally, the functionality is fine. There are some aspects that require further refinement:

* Our lettercasing uses camel-base based on word boundaries. Since `novalues` is a word on its own, method names should be `hscanNovalues` instead of `hscanNoValues`. We already have some mixture in letter casing. To align with how it should be, please use a lowercase `v` as in `Novalues`.
* Missing `@since` tags. The next release aims towards 7.0, so please add `@since 7.0` to all newly introduced `public` methods. Adding the tag into the template is typically fine.
* There are several unrelated changes such as changes to `RedisServerAsyncCommands` that result from committing all generated interfaces. Please remove these changes from the PR to have a focused pull request.

**Comment by gerzse** [comment]
> Generally, the functionality is fine. There are some aspects that require further refinement:
> 
> * Our lettercasing uses camel-base based on word boundaries. Since `novalues` is a word on its own, method names should be `hscanNovalues` instead of `hscanNoValues`. We already have some mixture in letter casing. To align with how it should be, please use a lowercase `v` as in `Novalues`.
> * Missing `@since` tags. The next release aims towards 7.0, so please add `@since 7.0` to all newly introduced `public` methods. Adding the tag into the template is typically fine.
> * There are several unrelated changes such as changes to `RedisServerAsyncCommands` that result from committing all generated interfaces. Please remove these changes from the PR to have a focused pull request.

Thanks for the review!

* I did notice in the codebase the drift in the naming rules. I will switch to the one that you suggested. Also I'll add tags.
* About the unrelated changes, you're right, they don't belong here. What happened is that I ran the code generator and got many differences, so I though doing something about that. I will open a separate PR only about aligning the templates with the current state of the code, if it's OK.
* Besides this, @atakavci pointed out that I missed some interfaces that have the `hscan` method, so I'll try to cover those too, since `hscanNovalues` is a general alternative to `hscan`.

**Comment by gerzse** [comment]
> > Generally, the functionality is fine. There are some aspects that require further refinement:
> > 
> > * Our lettercasing uses camel-base based on word boundaries. Since `novalues` is a word on its own, method names should be `hscanNovalues` instead of `hscanNoValues`. We already have some mixture in letter casing. To align with how it should be, please use a lowercase `v` as in `Novalues`.
> > * Missing `@since` tags. The next release aims towards 7.0, so please add `@since 7.0` to all newly introduced `public` methods. Adding the tag into the template is typically fine.
> > * There are several unrelated changes such as changes to `RedisServerAsyncCommands` that result from committing all generated interfaces. Please remove these changes from the PR to have a focused pull request.
> 
> Thanks for the review!
> 
> * I did notice in the codebase the drift in the naming rules. I will switch to the one that you suggested. Also I'll add tags.
> * About the unrelated changes, you're right, they don't belong here. What happened is that I ran the code generator and got many differences, so I though doing something about that. I will open a separate PR only about aligning the templates with the current state of the code, if it's OK.
> * Besides this, @atakavci pointed out that I missed some interfaces that have the `hscan` method, so I'll try to cover those too, since `hscanNovalues` is a general alternative to `hscan`.

The code generator is a bit of Pandora's box, which I don't want to open. I ran the generator, reverted all the (quite many) unrelated changes, and kept strictly the changes related to HSCAN NOVALUES.

**Review by atakavci — APPROVED** [review]
looks good!

**Review by mp911de — APPROVED** [review]

**Comment by mp911de** [comment]
@atakavci @tishun feel free to merge.

**Pull request merged**
